### ISSUE TITLE
你好，我训练代码的时候发现训练集缺少部分文件

### ISSUE THREAD

**Issue by qingchenkanlu** [THU-DA-6D-Pose-Group/CATRE#1]
FileNotFoundError: [Errno 2] No such file or directory: '/media/yusheng/F/code/CATRE-main/datasets/NOCS/REAL/real_train/mug_handle.pkl'
如果方便的话麻烦补充一下，谢谢！

**Comment by qingchenkanlu** [comment]
没事了，谢谢，找到了。。。

**Comment by SiyuWang0906** [comment]
This article is brilliant, I want to run and learn this code.
When I running the code pose_data.py for generate the dataset, there would always be an error:
Traceback (most recent call last):
File "./CATRE-main/CATRE-main/preprocess/pose_data.py", line 552, in
annotate_test_data(data_dir)
File "./CATRE-main/CATRE-main/preprocess/pose_data.py", line 475, in annotate_test_data
gt_class_ids = nocs["gt_class_ids"]
KeyError: 'gt_class_ids'
I tried download the data several times, the data .pkls still miss the key ['gt_class_ids'] ... only have two keys: image_path and gt_RTs,
这个遇到过没

**Comment by qingchenkanlu** [comment]
兄弟不用跑这个代码了，我跑通了，达不到论文里面的效果，而且很难调通

**Comment by SiyuWang0906** [comment]
作者新上传的文件跑了一下好像效果还可以

**Comment by Avocadoooooo** [comment]
> This article is brilliant, I want to run and learn this code. When I running the code pose_data.py for generate the dataset, there would always be an error: Traceback (most recent call last): File "./CATRE-main/CATRE-main/preprocess/pose_data.py", line 552, in annotate_test_data(data_dir) File "./CATRE-main/CATRE-main/preprocess/pose_data.py", line 475, in annotate_test_data gt_class_ids = nocs["gt_class_ids"] KeyError: 'gt_class_ids' I tried download the data several times, the data .pkls still miss the key ['gt_class_ids'] ... only have two keys: image_path and gt_RTs, 这个遇到过没

请问这个怎么解决呀
