### ISSUE TITLE
Question about mean model points

### ISSUE THREAD

**Issue by taeyeopl** [THU-DA-6D-Pose-Group/CATRE#12]
Q1. The [mean shapes](https://github.com/THU-DA-6D-Pose-Group/CATRE/blob/main/datasets/NOCS/obj_models/cr_normed_mean_model_points_spd.pkl) differ from [SPD](https://github.com/mentian/object-deformnet) mean shape. I wonder how you get mean shape. 

Q2. May I ask why you added a shuffle during the loading mean model points?

https://github.com/THU-DA-6D-Pose-Group/CATRE/blob/a0b42b5bc10727ab3f572d5eef53628bd778c7f2/core/catre/datasets/data_loader.py#L376

**Comment by shanice-l** [comment]
Hi,
Q1: The mean shape is derived from SPD. For adjusting CATRE, we rescaled the range to [-1, 1].

Q2: There is no special reason. I've done related experiments and found that the shuffle operation won't affect the results.

**Comment by taeyeopl** [comment]
Thanks for your quick replies. 

Regarding Q1, do you have any reason for rescaling the range to [-1, 1]? Does this improve the performance?

**Comment by shanice-l** [comment]
Because we also refine the estimated scale, in the code we multiply the mean shape with s_{est}.

**Comment by taeyeopl** [comment]
Thanks, Is this part what you say? 

https://github.com/THU-DA-6D-Pose-Group/CATRE/blob/a0b42b5bc10727ab3f572d5eef53628bd778c7f2/core/catre/engine/batch_test.py#L85-L90

**Comment by shanice-l** [comment]
Yes.

**Comment by taeyeopl** [comment]
Thanks for your replies :)

**Comment by taeyeopl** [comment]
@shanice-l Can you explain how do you get mean_scale?

https://github.com/THU-DA-6D-Pose-Group/CATRE/blob/a0b42b5bc10727ab3f572d5eef53628bd778c7f2/ref/nocs.py#L105-L112

The values are slightly different when I check using the mean scale from SPD mean shape. 
`np.abs(self.mean_model[class].max(0)) / 2 `

 mean_scale = { 
     "bottle": array([0.07624906, 0.21785153, 0.07224454]), 
     "bowl": array([0.16847943, 0.06134908, 0.16105685])
     "camera":array([0.09654312, 0.11487991, 0.16583854])
     "can":array([0.11170839, 0.18665881, 0.11039044])
     "laptop":array([0.1408229 , 0.10234819, 0.16517451])
     "mug": array([0.18962663, 0.11490806, 0.10203232]), 
 }

**Comment by shanice-l** [comment]
The code is borrowed from [GPV-Pose](https://github.com/lolrudy/GPV_Pose/blob/5828345126aad60213360132fe38a13a6b0cb4c1/datasets/load_data.py#L324)
