### ISSUE TITLE
prepare_spd_init_results for the CAMERA25 val set

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [THU-DA-6D-Pose-Group/CATRE#13]
Hi, thanks for sharing the code. 

I tried to modify the prepare_spd_init_results.py for the CAMERA val set, but some errors occurred. The results in the mrcnn_results folder seem not complete, and, in some cases, the number of the detected masks is not equal to the predicted class numbers. Would you like to share the spd_init_results for the CAMERA25 val set, or could you please share how you address the errors?  Looking forward to hearing from you!

**Comment by shanice-l** [comment]
Hi, I've uploaded the file in the latest [commit](https://github.com/THU-DA-6D-Pose-Group/CATRE/commit/89b1b375d38cf4cc2286912522628d2266d8c41b).

**Comment by Lynne-Zheng-Linfang** [comment]
Thanks!
