### ISSUE TITLE
Would you like to share the posecnn_init_results

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [THU-DA-6D-Pose-Group/CATRE#14]
Hi, thanks for sharing the code. I am wondering if you would like to share the initial pose file for the posecnn. I have tried to download the posecnn results by myself, but the results seem incorrect. Looking forward to hearing from you!

**Comment by shanice-l** [comment]
Sorry for the late reply. I use the PoseCNN results produced by DeepIM, which are might not publicly available.
