### ISSUE TITLE
Question about the reported inference speed 85.32Hz

### ISSUE THREAD

**Issue by Van5SE** [THU-DA-6D-Pose-Group/CATRE#15]
Hi! Thank you for your code . I would like to ask if the inference speed **85.32 Hz** reported in the paper includes the inference time of Mask RCNN？
Thank you for your reply!

**Comment by shanice-l** [comment]
Yes, it includes the segmentation time.

**Comment by shanice-l** [comment]
The tracking time only includes one-step refinement, so it's very very fast.
