### ISSUE TITLE
Generating the dataset -- NCOS gts problem

### ISSUE THREAD

**Issue by SiyuWang0906** [THU-DA-6D-Pose-Group/CATRE#6]
Hi dear.
This article is brilliant,  I want to run and learn this code.
When I running the code pose_data.py for generate the dataset, there would always be an error:
Traceback (most recent call last):
  File "./CATRE-main/CATRE-main/preprocess/pose_data.py", line 552, in <module>
    annotate_test_data(data_dir)
  File "./CATRE-main/CATRE-main/preprocess/pose_data.py", line 475, in annotate_test_data
    gt_class_ids = nocs["gt_class_ids"]
KeyError: 'gt_class_ids'
I tried download the data several times, the data .pkls  still miss the key ['gt_class_ids'] ... only have two keys: image_path and gt_RTs, 
I hope that you can help me with this problem, thanks!

**Comment by shanice-l** [comment]
I've uploaded a new script that changed the gt path. You can download the nocs_results from [here](https://drive.google.com/file/d/1p72NdY4Bie_sra9U8zoUNI4fTrQZdbnc/view).
